name: ServerRules
main: ServerRules\ServerRules
version: 1.0.0
api: 3.0.0-ALPHA10

author: kenygamer
description: A PocketMine-MP plugin to list your rules in one command

commands:
 rules:
  description: Server rules.
  usage: "/rules [page]"
  permission: rules

permissions:
 rules:
  description: Allows access to the rules command
  default: true
